<?php
/**
 * Created by PhpStorm.
 * User: yvan
 * Date: 9/18/16
 * Time: 7:45 PM
 */

namespace App;


use Illuminate\Database\Eloquent\Model;

class Student extends Model
{
    const SEX_U=10;
    const SEX_M=20;
    const SEX_F=30;


    protected $table='student';

    protected $primaryKey='id';

    protected $guarded=[];

    public $timestamps=true;

    protected  function getDateFormat()
    {
        return time(); // TODO: Change the autogenerated stub
    }
    protected function asDateTime($value)
    {
        return $value; // TODO: Change the autogenerated stub
    }

    public function sex($s=null){
        $arr=[
            self::SEX_U=>'Unknown',
            self::SEX_M=>'Male',
            self::SEX_F=>'Female',
        ];
        if($s)
            return array_key_exists($s, $arr) ? $arr[$s] :$arr[self::SEX_U] ;
        return $arr;
    }
}